# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - with:
          node-version: 16
          cache: yarn
      - run: yarn test

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - with:
          node-version: 16
          cache: yarn
      - run: yarn test
